<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\Img__OK.png" />
    <None Remove="Images\IMG__WinClose.png" />
    <None Remove="Images\IMG__WinMax.png" />
    <None Remove="Images\IMG__WinMin.png" />
    <None Remove="Images\IMG__WinRest.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Img__OK.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\IMG__WinClose.png" />
    <Resource Include="Images\IMG__WinMax.png" />
    <Resource Include="Images\IMG__WinMin.png" />
    <Resource Include="Images\IMG__WinRest.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
